'use client'

import { useState } from 'react'
import { AlertTriangle } from 'lucide-react'
import { Modal } from './modal'
import { Button } from './button'

interface DisclaimerProps {
  isOpen: boolean
  onAccept: () => void
  onDecline: () => void
}

export function Disclaimer({ isOpen, onAccept, onDecline }: DisclaimerProps) {
  return (
    <Modal isOpen={isOpen} onClose={onDecline} title="Important Legal Notice" size="lg">
      <div className="space-y-4">
        <div className="flex items-start gap-3 p-4 bg-amber-50 border border-amber-200 rounded-lg">
          <AlertTriangle className="w-5 h-5 text-amber-600 mt-0.5 flex-shrink-0" />
          <div>
            <p className="font-medium text-amber-800">Please Read Carefully</p>
            <p className="text-sm text-amber-700 mt-1">
              This is a critical disclaimer about the nature of our service.
            </p>
          </div>
        </div>

        <div className="space-y-3 text-sm text-slate-600">
          <p className="font-medium text-slate-800">Legality Does NOT Provide Legal Advice</p>
          <p>
            <strong>Legality</strong> is an educational and informational tool only. The information
            provided through this application:
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Is generated by artificial intelligence and should not be considered legal counsel</li>
            <li>Does not create an attorney-client relationship</li>
            <li>May not be accurate, complete, or applicable to your specific situation</li>
            <li>Should never replace consultation with a licensed attorney</li>
          </ul>
          <p>
            By using this service, you acknowledge that you understand the information provided is for
            educational purposes only and is not a substitute for professional legal advice.
          </p>
          <p>
            Laws vary significantly by jurisdiction, and legal matters are highly fact-specific. What
            may seem similar to your situation could have very different legal implications based on
            the specific circumstances and applicable law.
          </p>
        </div>

        <div className="border-t border-slate-200 pt-4">
          <label className="flex items-start gap-3 cursor-pointer">
            <input
              type="checkbox"
              onChange={(e) => {
                if (e.target.checked) onAccept()
              }}
              className="mt-1 h-4 w-4 rounded border-slate-300 text-primary focus:ring-primary-500"
            />
            <span className="text-sm text-slate-600">
              I have read and understood this disclaimer. I acknowledge that Legality does not
              provide legal advice and that I should consult with a licensed attorney for any legal
              matter.
            </span>
          </label>
        </div>

        <div className="flex justify-end gap-3 pt-2">
          <Button variant="ghost" onClick={onDecline}>
            Decline
          </Button>
        </div>
      </div>
    </Modal>
  )
}

export function DisclaimerBanner() {
  return (
    <div className="bg-amber-50 border-b border-amber-200 px-4 py-2">
      <div className="max-w-4xl mx-auto flex items-center gap-2 text-sm text-amber-800">
        <AlertTriangle className="w-4 h-4 flex-shrink-0" />
        <span>
          <strong>Disclaimer:</strong> This service provides educational information only, not legal
          advice. Always consult a licensed attorney for legal matters.
        </span>
      </div>
    </div>
  )
}
